"""initial_schema

Revision ID: ecb65454b9f3
Revises: 
Create Date: 2026-09-19 16:42:59.495768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa #type: ignore


# revision identifiers, used by Alembic.
revision: str = 'ecb65454b9f3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'REVIEWER', 'USER', name='userrole', native_enum=False, length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('documents',
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('doc_type', sa.Enum('QUESTION_PAPER', 'ANSWER_KEY', 'COMBINED', 'UNKNOWN', name='documenttype', native_enum=False, length=50), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PREPROCESSING', 'EXTRACTING', 'ASSOCIATING_ANSWERS', 'COMPLETED', 'FAILED', 'NEEDS_REVIEW', name='documentstatus', native_enum=False, length=50), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_file_hash'), ['file_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_status'), ['status'], unique=False)

    op.create_table('document_relationships',
    sa.Column('source_document_id', sa.String(length=36), nullable=False),
    sa.Column('target_document_id', sa.String(length=36), nullable=False),
    sa.Column('relationship_type', sa.Enum('ANSWER_KEY_FOR', 'SUPPLEMENTARY_TO', 'SAME_EXAM', name='relationshiptype', native_enum=False, length=50), nullable=False),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_document_id', 'target_document_id', 'relationship_type', name='uq_document_relationship')
    )
    with op.batch_alter_table('document_relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_relationships_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_relationships_source_document_id'), ['source_document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_relationships_target_document_id'), ['target_document_id'], unique=False)

    op.create_table('questions',
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('question_number', sa.String(length=64), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.Enum('MULTIPLE_CHOICE', 'MULTIPLE_SELECT', 'TRUE_FALSE', 'FILL_IN_THE_BLANK', 'SUBJECTIVE', 'MATCH_FOLLOWING', 'UNKNOWN', name='questiontype', native_enum=False, length=50), nullable=False),
    sa.Column('source_pages', sa.JSON(), nullable=False),
    sa.Column('bounding_boxes', sa.JSON(), nullable=True),
    sa.Column('diagram_paths', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('review_status', sa.Enum('CONFIDENT', 'NEEDS_REVIEW', 'PARTIAL_EXTRACTION', 'RESOLVED', name='reviewstatus', native_enum=False, length=50), nullable=False),
    sa.Column('raw_extraction', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_question_number'), ['question_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_review_status'), ['review_status'], unique=False)

    op.create_table('answer_keys',
    sa.Column('question_id', sa.String(length=36), nullable=True),
    sa.Column('source_document_id', sa.String(length=36), nullable=False),
    sa.Column('question_identifier', sa.String(length=64), nullable=False),
    sa.Column('raw_answer_text', sa.Text(), nullable=False),
    sa.Column('normalized_answer', sa.String(length=256), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('match_status', sa.Enum('MATCHED', 'AMBIGUOUS', 'UNMATCHED', name='answermatchstatus', native_enum=False, length=50), nullable=False),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('answer_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_answer_keys_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_answer_keys_match_status'), ['match_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_answer_keys_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_answer_keys_question_identifier'), ['question_identifier'], unique=False)
        batch_op.create_index(batch_op.f('ix_answer_keys_source_document_id'), ['source_document_id'], unique=False)

    op.create_table('extraction_warnings',
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=True),
    sa.Column('warning_code', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='warningseverity', native_enum=False, length=50), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('is_dismissed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extraction_warnings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extraction_warnings_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_extraction_warnings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_extraction_warnings_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_extraction_warnings_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_extraction_warnings_warning_code'), ['warning_code'], unique=False)

    op.create_table('question_options',
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('option_key', sa.String(length=32), nullable=False),
    sa.Column('option_text', sa.Text(), nullable=False),
    sa.Column('diagram_path', sa.String(length=1024), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_options_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_options_question_id'), ['question_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_options_question_id'))
        batch_op.drop_index(batch_op.f('ix_question_options_id'))

    op.drop_table('question_options')
    with op.batch_alter_table('extraction_warnings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extraction_warnings_warning_code'))
        batch_op.drop_index(batch_op.f('ix_extraction_warnings_severity'))
        batch_op.drop_index(batch_op.f('ix_extraction_warnings_question_id'))
        batch_op.drop_index(batch_op.f('ix_extraction_warnings_id'))
        batch_op.drop_index(batch_op.f('ix_extraction_warnings_document_id'))

    op.drop_table('extraction_warnings')
    with op.batch_alter_table('answer_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_answer_keys_source_document_id'))
        batch_op.drop_index(batch_op.f('ix_answer_keys_question_identifier'))
        batch_op.drop_index(batch_op.f('ix_answer_keys_question_id'))
        batch_op.drop_index(batch_op.f('ix_answer_keys_match_status'))
        batch_op.drop_index(batch_op.f('ix_answer_keys_id'))

    op.drop_table('answer_keys')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_review_status'))
        batch_op.drop_index(batch_op.f('ix_questions_question_number'))
        batch_op.drop_index(batch_op.f('ix_questions_id'))
        batch_op.drop_index(batch_op.f('ix_questions_document_id'))

    op.drop_table('questions')
    with op.batch_alter_table('document_relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_relationships_target_document_id'))
        batch_op.drop_index(batch_op.f('ix_document_relationships_source_document_id'))
        batch_op.drop_index(batch_op.f('ix_document_relationships_id'))

    op.drop_table('document_relationships')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_status'))
        batch_op.drop_index(batch_op.f('ix_documents_owner_id'))
        batch_op.drop_index(batch_op.f('ix_documents_id'))
        batch_op.drop_index(batch_op.f('ix_documents_file_hash'))

    op.drop_table('documents')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
